### ISSUE TITLE
[Discussion] Detection Architecture

### ISSUE THREAD

**Issue by kfunaoka** [autowarefoundation/autoware_ai#288]
# New Design
<img width="550" alt="43500108-dbe7a948-9589-11e8-80c7-8c5c307eabe6" src="https://user-images.githubusercontent.com/38030772/45199868-05b89480-b2a9-11e8-89c0-3114b929525a.png">
The design above doesn't have vision_tracker. vision_tracker can't belong to object_tracker because vision_tracker tracks only the results of vision_detector. This issue is where we discuss how the fusion should be.

| Component | Node Example |
|-----------|------------|
|  vision_detector | Yolo3 |
| vision_tracker | Beyond Pixel |
| lidar_detector | Euclidean Cluster |

**Comment by kfunaoka** [comment]
I’ve discussed the design with @amc-nu. If any question or suggestion, please let me know.

The conclusion now is:
* vision_tacker is inserted between vision_detector and range_vision_fusion in order to improve the input of range_vision_fusion and (as the rusult) object_tracker.
* object_tracker is not renamed (to e.g., lider_tracker) because it might uses the info (e.g., what the object is) come from vision_detector such as yolo3.
* At this moment, it seems that lidar_tracker between lidar_detector and range_vision_fusion is unnecessary because we have no algorithms that should be between lidar_detector and range_vision_fusion at least now.

<img width="411" alt="2018-09-07 13 30 41" src="https://user-images.githubusercontent.com/38030772/45199765-6398ac80-b2a8-11e8-9a77-094f33a546db.png">

**Comment by kfunaoka** [comment]
I've created a issue autowarefoundation/autoware_ai#368 for `General Guidelines for Architecture Design`.

We'll answer Dejan's questions about perception after ready.

**Comment by amc-nu** [comment]
@dejanpan here some answers to the questions from
https://github.com/CPFL/Autoware/issues/1501#issuecomment-431543021
1. Yes
2. It uses some image detector on the camera stream. Each node  is either based on a CNN or Machine learning  method. These are configurable. Custom models and definitions can be used.
3. Please have a look in the messages directory for the DetectedObject message 
4. Currently all the Detection workflow uses the same message definition DetectedObject. Each part is filled or updated through the detection  workflow .
5. Fuse boxes and rects from Vision and lidar detectors. The TF between lidar and camera is read only once (since that won’t be changing over time)
6.  The node can synchronize using http://wiki.ros.org/message_filters#Time_Synchronizer
7. Fusion_detector would output the detection already fused. Please check CNN based fusion object detector( Avod, MV3D, etc). The package is just a container for the time being.
8. In the case when vision tracker is not used we can still track objects using the Lidar tracker.

**Comment by amc-nu** [comment]
@dejanpan here some answers to the questions from
https://github.com/CPFL/Autoware/issues/1501#issuecomment-431543021
1. Yes
2. It uses some image detector on the camera stream. Each node  is either based on a CNN or Machine learning  method. These are configurable. Custom models and definitions can be used.
3. Please have a look in the messages directory for the DetectedObject message 
4. Currently all the Detection workflow uses the same message definition DetectedObject. Each part is filled or updated through the detection  workflow .
5. Fuses boxes and rects from Vision and lidar detectors. The TF between lidar and camera is read only once (since that won’t be changing over time)
6.  The node can synchronize using http://wiki.ros.org/message_filters#Time_Synchronizer
7. Fusion_detector would output the detection already fused. Please check CNN based fusion object detector( Avod, MV3D, etc). The package is just a container for the time being.
8. In the case when vision tracker is not used we can still track objects using the Lidar tracker.

**Comment by kfunaoka** [comment]
> @kfunaoka what tool did you use for diagram here: autowarefoundation/autoware_ai#288 (comment).

@dejanpan I'm using http://en.plantuml.com/. I'd like to know better tool.

I'll look into your comments in this issue and #proj-architecture tomorrow.
