### ISSUE TITLE
Build Error with Cuda9

### ISSUE THREAD

**Issue by andoh104** [autowarefoundation/autoware_ai#4]

**Comment by anhnv3991** [comment]
Install Cuda 8 instead of Cuda 9 can fix that problem.
Maybe some files included in ndt_gpu use the __CUDA_VER__ macro in the ‘if’ command to check the current CUDA version. However, in CUDA 9, that macro is defined as a string, not a number, so compare it with a number in the ‘if’ command is invalid.
