### ISSUE TITLE
[Feature] Autoware Maps: Next Generation Autoware Map Format

### ISSUE THREAD

**Issue by messi49** [autowarefoundation/autoware_ai#408]
# Design

We created the next generation map format for Autoware (called Autoware Maps Format).

### Goal 
- Make map format open format
- Make common format of Autoware and [AMS](https://github.com/CPFL/AMS)
- Change PCD format plane rectangular coordinate to MGRS in order to support global.

### Notification
- The vector map builder which is map editor for Autoware maps format will be released.

Please see this, then let's start to discuss.
https://docs.google.com/presentation/d/12vZzMfVLAjeuGSS7qykpzDjbOagJBBQJ7D33c-QtJPI/edit?usp=sharing

**Comment by inejose** [comment]
@messi49 regarding to the goal:

Change PCD format plane rectangular coordinate to MGRS(UTM) in order to support global.

we are stuck in this problem since some months, we would like to use Autoware in Europe with the appropriate UTM conversion but the methods and libraries suggested in  autowarefoundation/autoware_ai#79 autowarefoundation/autoware_ai#309 autowarefoundation/autoware_ai#880  and many others seem not to work. 

Please, could you provide some indications or code extract about this point before the release? We really appreciate it.

**Comment by messi49** [comment]
@JWhitleyAStuff Thank you for pointing it out.

> Is there a reason that a new format was chosen instead of an existing, open format such as OpenDRIVE (which is very popular in the autonomous vehicle space) or OSM XML or a CSV representation of an existing open format?

Other existing open format are too rich for Autoware.
New Autoware maps format is very simple and cost of creating map is low.
In addition, we will prepare the map converter (OpenDrive → Autoware Maps Format) in the future.

> I would also argue that what you're representing is essentially a relational database and something like PostGIS + PostgreSQL (which are both open-source) would be more portable and easily accessed than a group of CSV files. SpatiaLite is another alternative.

Yes, data architecture of Autoware maps format is essentially a relational database.
You can easily insert database with importing map data of Autoware maps format.

**Comment by shinpei0208** [comment]
Joshua,

The Autoware Maps format is used internally in Autoware so as to improve
computation time and keep source code as simple as possible. This format is
compatible with most of other existing formats, such as Open Drive. That
is, you can use Open Drive maps with Autoware, though internally they are
converted to the Autoware Maps format in order to maximize the real-time
performance of road feature searches.

Shinpei

2018年11月13日(火) 7:25、Joshua Whitley さん（notifications@github.com）のメッセージ:

**Comment by messi49** [comment]
@JWhitleyAStuff I respond to your questions with the following. 

> What is the difference between Waypoint::width and Lane::width_limit?

The Waypoint::width mean lane width at the point of waypoint.
The Lane::width_limit is the minimum value of waypoint of lane.

> Why would the waypoint define a width - isn't that only associated with a lane?

Lane area is defined by using the waypoint width.
Currently, Autoware use wayarea for detection.

> What is the difference between Waypoint::height and Lane::height_limit?

This is same relation between Waypoint::width and Lane::width_limit.
The Waypoint::height mean height limit at the point of waypoint.
The Lane::height_limit is the minimum value of waypoint of lane.
However, I think that the waypoint need not to have value of height limit with respect to height limit.

> What is the definition of Waypoint::yaw angle?

The waypoint::yaw mean the direction of vehicle driving.

> Is Waypoint::velocity the same as Speed Limit?

Yes.
Although the waypoint::velocity at corner is not always same.

> Is an Area always within a single lane? Can it cover multiple lanes? Can it exist outside of lanes?

An area can be referred to from multiple lanes.
It can exist outside of lanes.
A relation between lane and area is flexible.

> Will a lane always have exactly one start and one end waypoint?

Yes.
※The waypoint of junction is referred to from multiple lanes.

> If a road is too narrow for two cars to pass by each other (very common), will two lanes be defined with one waypoint being the start of one and the end of another and vice versa?

Yes.
There are another waypoints in each of the lane orientation.

> Will Lanes always be defined by a set of Waypoints or can Waypoints be outside of lanes?

The Lanes will always be defined by a set of Waypoints.

> What is the definition of Wayarea and how is it different than Area?

The wayarea is detection area of Autoware. ※The currently version Autoware  use wayarea.
However, we want Autoware to use waypoint width and area.

<br>
<br>
@dejanpan Thank you for comment.
The Lane attribute such as 4 way stop intersections can easily be added.

New Autoware maps format like intermediate representation of autoware used internally.
So, Autoware can support multiple map format by preparing the converter of OpenDrive, TomTom, Aisan.

**Comment by shinpei0208** [comment]
Guys, thanks for all the discussions and useful feedback here. To make it
clear, we will support those well-known map formats and Open Drive would be
a default format. They are *frontend* formats. The Autoware Maps, on the
other hand, is a backend map engine and thus its format is a backend
format. It could be converted to as many frontend maps, i.e., Open Drive
etc., so that as many map users as possible can use Autoware.

2018年11月15日(木) 13:19、Alexander Carballo さん（notifications@github.com）のメッセージ:

**Comment by alexandrx** [comment]
We can consider the implementation by Institute of Transportation Systems of the German Aerospace Center (Deutsche Zentrum für Luft- und Raumfahrt - DLR, http://www.dlr.de/ts/en), available at github:

https://github.com/DLR-TS/xodr

It uses XSD for code generation based on OpenDrive schemas. Need to make sure XSD license works for us.

**Comment by messi49** [comment]
We decided to use  Open Drive Format.
※Autoware Maps Format is data structure of internal process of Autoware.

![image](https://user-images.githubusercontent.com/2592546/48689305-37d16580-ec0d-11e8-824b-3cd28cddfa04.png)

**Comment by dejanpan** [comment]
@messi49 @shinpei0208 @JWhitleyAStuff @alexandrx @hadiTab 

I am a complete mapping noob but I took the time, did some reading and talked to some people that have done AD maps before. Here are my current findings:

In general an AD map consists of:
1. Data in exchange format => NDS`*`, gps, PointCloud, ...
2. Library to access above data + IO API
3. Map model
4. Data compiler => compiles the data from raw data in exchange format into a binary and faster loadable version.
5. Tools (e.g. visualizer)
6. Interface format
The most important above is the map model, interface format is secondary.

Map model is often built around the limited set of use cases but then people quickly start to run into issues with it. This is what happened before in Autoware and will happen again with above proposal.

Examples of map models:

1. Lanelet (or [Lanelet2](https://github.com/fzi-forschungszentrum-informatik/lanelet2)) is very good. No known drawbacks.

2. OpenDrive is meant for simulation. What is missing are topology, areas, conditions, AGV lanes, missing modeling relationships (traffic sign - lanes), …


Commercial options:

1. Here is offering a library and API, they have a model for AD driving. They also offer data in the compiled format. They have a very good documentation. However the they do not have a point cloud data.

2. Deepmap, they offer a black box solution (mapping and localization) and also API for maps.



`*` NDS - data definition language, also provides reference implementation for library and api. It is more used for navigation systems. It basically defines the PSF (physical storage format) for the map data.

@messi49 @shinpei0208 @JWhitleyAStuff @alexandrx @hadiTab  can you confirm or deny my comprehension above? 

To me it now seems that we have 3 options:
1. OpenDrive + https://github.com/DLR-TS/xodr. With this solution it seems that OpenDrive model lacks important features and I do not know how it includes data in exchange format and what tools are available for debugging/visualization. 
    - @alexandrx could we use https://github.com/DLR-TS/xodr directly in the Autoware algorithms?
1. We go with Here. But them not having PointClouds in the map is probably a no-go.
1. We go with Lanelet2. This to me is currently the best option.

**Comment by dejanpan** [comment]
@JWhitleyAStuff @sgvandijk @alexandrx @hadiTab @messi49 @shinpei0208  sorry for late reply. 

I have pinged 3 mapping experts and here is what I have learnt in addition. 

### Lanelet2 (conversation with the creator Fabian Poggenhans)
1. It is a 2nd shot (after original Lanelet) and put out there to wait for the feedback from the users
1. Their IO interface is based on open street map (OSM)
1. Geo-referenced large data (images, pointclouds) are not included in the map
1. They have functions to project between the lat/lon geographic world and local metric coordinates (currently implemented WGS 84)
1. you can use [JOSM](https://josm.openstreetmap.de/) to visualize and modify maps 
1. They do not use tiling and do not use data compiler (point 4 above)
1. Visualization in RVIZ => working on it
1. Most supported use case: Navigation, planning the route on the lane level, prediction of other participants 
1. Currently not supported use case: no LiDAR-based localization
1. Otherwise Lanelet2 checks all other boxes mentioned here: https://github.com/CPFL/Autoware/issues/1701#issuecomment-440518903
1. Algorithm developers are supposed to use their [data structures](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_core/include/lanelet2_core) and [IO modules](https://github.com/fzi-forschungszentrum-informatik/Lanelet2/tree/master/lanelet2_io) in their algorithms.

I also asked Fabian about the map model proposed by @messi49  and this was his reply:

> The approach of tagging all the information to waypoints reminds me a bit of the Opendrive approach. Our experience with this is, that such an approach generalizes very badly to real scenarios. Over the time more and more specific information is required and more and more tags must be added (for other participants, for different traffic signs, other countries, etc). In the end, the number of tags gets so complex that it is really hard to “debug” or understand the map data. This is why Lanelet2 uses a more “physically” motivated approach to tagging.
> 
> 
> Also the representation of the lane width makes it very hard to get the original shape of the lane back. This is often important when you want to predict if other participants interfere with the current trajectory. It gets even harder when the road elevation is considered as well. Also it is harder to find changes in the map if the original lane boundaries are lost.

They would be willing to accommodate changes and possibly we could even contract them from the Autoware foundation.

### OpenDrive
OpenDrive is in the process of becoming an industry standard and there are at least two companies out there which can produce OpenDrive maps. There is a bunch of software which can import (parts of) OpenDrive. 

From a technical view, OpenDrive is strongly tied to the idea of reference lines. Each road has a reference line which is an axis of a curved coordinate system. Road borders are described in this coordinate system (as splines describing the lateral offset from reference line). This works nicely in many situations and provides smooth (mathematically differentiable) descriptions of laneborders. This is good, two, especially for simulations. However, it has drawbacks. For some real situations, it is difficult to describe lane borders in terms of that curved coordinate system. 

Another weakness is that the standard is sometimes too generic. It says that there can be objects and how these can be described, but it does not define a standard on how to model certain objects like Guardrails, Crosswalks etc. 

But maybe the largest drawback is in describing traffic rules. You can place objects like holding lines in the model, but you cannot clearly describe what the car has to wait for on that line (is it a traffic light, is it a yield situation, is it a crosswalk?)

This above is basically in line with what @JWhitleyAStuff has stated above too.

### Conclusion
From everything above I would suggest that we pick Lanelet2 as a library for handling map data in Autoware (including its map model and APIs). I see following advantages compare to @messi49 proposal and OpenDrive:
1. It is open-source and very well thought through
1. It is quite proven (based on Lanelet)
1. It is flexible and extensible
1. It comes in as a full package
1. It moves away from the idea of reference lines to a more physically feasible approach

I agree with @JWhitleyAStuff that the project is young but 
1. it is tested and under CI: https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/.gitlab-ci.yml
1. very nicely written and documented, e.g. https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/include/lanelet2_core/geometry/Area.h

It would be great if we could agree on this by the end of this week.
