### ISSUE TITLE
Map coordinate

### ISSUE THREAD

**Issue by rxq19951101** [autowarefoundation/autoware_ai#513]

**Comment by mitsudome-r** [comment]
In order to use gnss for ndt, origin of pointcloud and gnss_pose must be same.
In your case, the origin of your pointcloud must be the origin of your UTM zone.
If your gnss_pose is (x,y) at origin of your pointcloud, first you must shift the pointcloud by (x,y). 
Then, you have to rotate the pointcloud so that east is x. 

You can transform pointcloud using pcl_transform_pointcloud. See autowarefoundation/autoware_ai#496.
