### ISSUE TITLE
New Obstacle Avoidance Algorithm

### ISSUE THREAD

**Issue by huckl3b3rry87** [autowarefoundation/autoware_ai#67]

**Comment by amc-nu** [comment]
Hello @huckl3b3rry87 
I’ve been following all the stuff you’ve working on. Everything look interesting. Could you please
1.  tell us more about it. Write a short README for your package on how to use, test, etc.
1.  merge develop branch into your PR 
1.  target your PR to develop branch instead of master.
I’ll check it

Also can you tell us more about you. Are you a professor?, student? I can see you belong to UMich.

Thanks! Looking forward to hear about you and your projects.
