### ISSUE TITLE
Invoking make -j16 failed 

### ISSUE THREAD

**Issue by claretway** [autowarefoundation/autoware_ai#945]

**Comment by travelbureau** [comment]
Output says -j48 right before it fails not sure what behavior to expect but
I'm doubting you have 48 cores (although it's not impossible) also -l48
seems suspect perhaps some typo in build script?

On Jul 21, 2017 6:34 PM, "claretway" <notifications@github.com> wrote:

I was on master

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CPFL/Autoware/issues/737#issuecomment-317128067>, or mute
the thread

**Comment by travelbureau** [comment]
Would definitely try -j4 or -j8. On my 32gb ram workstation I have ran into
memory issues when building with a lot of cores, but sounds like there
might be something else going on as well.
